<a href="https://colab.research.google.com/github/lsp-sandeep/scaler_dsml_practice/blob/main/Week_5_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 2, 3, 4, 5, 6, 7])

A

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
print(A + 1)
print(list(map(lambda x:x+1, A)))
print([x+1 for x in A])

[2 3 4 5 6 7 8]
[2, 3, 4, 5, 6, 7, 8]
[2, 3, 4, 5, 6, 7, 8]


In [ ]:
print(np.arange(22, 71, 2))
print(np.arange(21, 72, 2))

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]
[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


In [ ]:
A = np.arange(1, 10)

A.shape

(9,)

In [ ]:
A = A.reshape(3, 3)

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.T[:, ::-1]

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [ ]:
A = [1, 2, 3, 4, 54 ,6 ,7, 9]

A[4:1:-1]

[54, 4, 3]

In [ ]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10]).reshape(2,-1)
x[(x >= -5) & (x <= 15)] *= -1 
x

array([[  5,  -9,  20,  25],
       [  3,  -5,  16, -10]])

In [ ]:
x = np.arange(1,21).reshape(4,-1)
print(x[::-1, ::-1])
print(x.T)
x

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.dot(x, x)

ValueError: ignored

In [ ]:
_.shape

(4, 4)

In [ ]:
A = np.arange(100).reshape(10, -1)

mask_0 = np.flip(np.argsort(A, axis = 0), axis = 0)
mask_1 = np.flip(np.argsort(A, axis = 1), axis = 1)

print(mask_0)
print(mask_1)

[[9 9 9 9 9 9 9 9 9 9]
 [8 8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 7 7 7]
 [6 6 6 6 6 6 6 6 6 6]
 [5 5 5 5 5 5 5 5 5 5]
 [4 4 4 4 4 4 4 4 4 4]
 [3 3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]]
[[9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]
 [9 8 7 6 5 4 3 2 1 0]]


In [ ]:
A[list(mask)]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


IndexError: ignored

In [ ]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
A[mask_0, mask_1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [ ]:
A[mask_0, np.tile(np.arange(10),(10,1))]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
def update_height_1(height,delta):

    height = np.array(height)

    delta = np.array(delta)

    new_height = height+delta 

    return new_height

def update_height_2(height, delta):

    new_height=[]

    for i in range(len(height)):
        new_height.append(height[i]+delta[i])

    return new_height

In [ ]:
height = list(range(100000))
del_height = list(range(100000))

%timeit update_height_1(height, del_height)

%timeit update_height_2(height, del_height)

100 loops, best of 5: 13.7 ms per loop
100 loops, best of 5: 15.6 ms per loop


In [ ]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [ ]:
arr1=np.array(['Ram','Astha','Brahat'])
arr2=np.array(['Shyam','Kalyan','Naveen'])
arr1>arr2

array([False, False, False])

In [ ]:
np.hstack([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a = _

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a = np.arange(12).reshape(3, 4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = np.arange(4).reshape(1, 4)

b

array([[0, 1, 2, 3]])

In [ ]:
c = np.concatenate([a, b], axis = 0)

c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [ ]:
np.concatenate([c, b.T], axis = 1)

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  1],
       [ 8,  9, 10, 11,  2],
       [ 0,  1,  2,  3,  3]])

In [ ]:
d = np.arange(9).reshape(3, 3)

d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.concatenate([d, d])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
e = np.concatenate([[d], [d]], axis = 2)

e

array([[[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]]])

In [ ]:
e.shape

(1, 3, 6)

In [ ]:
X = np.arange(12).reshape(3,4)

X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
X.max(axis=1)

array([ 3,  7, 11])

In [ ]:
X.T.max(axis=0)

array([ 3,  7, 11])

In [ ]:
[i.min() for i in X]

[0, 4, 8]

In [ ]:
X.sum()

66

In [ ]:
arr = np.arange(12)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [ ]:
np.all(arr > -1)

True

In [ ]:
np.dot(arr > 2, arr % 2 == 0)

True

In [ ]:
(arr > 2) * (arr % 2 == 0)

array([False, False, False, False,  True, False,  True, False,  True,
       False,  True, False])

In [ ]:
arr = 2*np.arange(0,2,0.5)
if arr <= 0.6:
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy")

ValueError: ignored

In [ ]:
a = np.arange(12).reshape(3,4)

a[:, 3]

array([ 3,  7, 11])

In [ ]:
a = [[1, 2, 3]]*3

a

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [ ]:
arr = np.array(a)

arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
arr[:, 2]

array([3, 3, 3])

In [ ]:
arr = np.arange(16).reshape(4,4)

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.split(arr, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
arr = np.arange(10)
np.split(arr, 3)

ValueError: ignored

In [ ]:
arr = np.arange(10)
np.split(arr, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
arr = np.arange(10)
np.split(arr, [2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
arr = np.arange(10)
np.split(arr, [5, 12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]

In [ ]:
c = np.zeros(10, dtype= int)

In [ ]:
a = np.arange(30).reshape(3, 10)
b = np.arange(30).reshape(10, 3)

a, b

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]))

In [ ]:
np.concatenate([a, c], axis = 0)

ValueError: ignored

In [ ]:
np.concatenate([a, c], axis = 1)

ValueError: ignored

In [ ]:
np.concatenate([c, a], axis = 0)

ValueError: ignored

In [ ]:
np.concatenate([c, a], axis = 1)

AxisError: ignored

In [ ]:
a = np.arange(4)
c = a

for i in range(a.size):
    c[i] = a[i] + 1

np.shares_memory(a, c)

array([1, 2, 3, 4])

In [ ]:
np.shares_memory(a, c)

True

In [ ]:
a = np.arange(4).reshape(1,1,1,4)

a

array([[[[0, 1, 2, 3]]]])

In [ ]:
a = np.arange(4)

a

array([0, 1, 2, 3])

In [ ]:
b = a[0]

b

0

In [ ]:
np.shares_memory(a, b)

False

In [ ]:
a[0] = 1
b

0

In [ ]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [ ]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])


arr1= np.array([[2,2,2,2]])
def func(x,y):
    return x*y
vec= np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
arr1= np.array([[2],[2],[2],[2]])
def func(x,y):
        return x*y
vec= np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
arr1= 2   
def func(x,y):
    return x*y
vec= np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(X[row[:, np.newaxis], mask])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [ ]:
a=np.array([[[ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0]],
[[ 0, 0, 255],
 [255, 255, 255],
 [ 0, 0, 0],
 [255, 0, 0]]])
b = [255,0,255]
c = np.all(a==b,axis=1)
print(c) 

[[False  True False]
 [False False False]]


In [ ]:
a == b

array([[[False,  True, False],
        [False,  True, False],
        [False,  True, False],
        [False,  True, False]],

       [[False,  True,  True],
        [ True, False,  True],
        [False,  True, False],
        [ True,  True, False]]])

In [ ]:
arr = np.array([2, 4, 6 ,8 ,10])
c0 = arr.view()
arr[0] = 12
arr = np.array([2, 4, 6 ,8 ,10])
c0

array([12,  4,  6,  8, 10])

In [ ]:
np.shares_memory(arr, c0)

False

In [ ]:
c1 = arr.view()

np.shares_memory(arr, c1)

True

In [ ]:
x = np.array([[12, 18], [3, 24], [0, 1], [5, 12]])

def func(arg):
    return ",".join(map(str, arg))

np.array(list(map(func, x)))

array(['12,18', '3,24', '0,1', '5,12'], dtype='<U5')

In [ ]:
np.apply_along_axis(func, 1, x)

array(['12,18', '3,24', '0,1', '5,12'], dtype='<U5')

In [ ]:
x = np.array([['peter', 'parker'], ['john', 'wick'], ['abc', 'xyz'], ['iron', 'man']])

np.apply_along_axis(",".join, 1, x)

array(['peter,parker', 'john,wick', 'abc,xyz', 'iron,man'], dtype='<U12')

In [ ]:
#np.apply_over_axes(",".join, x, [0])

In [ ]:
x = np.array([['peter', 'parker'], ['john', 'wickfjhgsoldhfgolsh'], ['abc', 'xyz'], ['iron', 'man']])

x_1, x_2 = np.split(x, 2, axis=1)

print(np.apply_along_axis(','.join, 0, [x_1, x_2]))

[['peter,parker']
 ['john,wickfjh']
 ['abc,xyz']
 ['iron,man']]


In [ ]:
x.dtype = '<U38'

In [ ]:
type("hauithauiwehtauiwth")

str

In [ ]:
x

array([['peter\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00parker'],
       ['john\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00wickfjhgsoldhfgolsh'],
       ['abc\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00xyz'],
       ['iron\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00man']],
      dtype='<U38')

In [ ]:
x = np.array([['peter', 'parker'], ['michael', 'jackson'], ['abc', 'xyz'], ['iron', 'man'], ['captain', 'shaktiman']])

nplen = np.vectorize(len)

idx = np.flip(np.argsort(np.sum(nplen(x), 1)))

x_new = x[idx, :]

y = np.apply_along_axis(",".join, 1, x_new)

y[np.argsort(idx)]

array(['peter,parker', 'michael,jackson', 'abc,xyz', 'iron,man',
       'captain,shaktiman'], dtype='<U17')

In [ ]:
np.apply_along_axis(",".join, 1, x_new)

array(['captain,shaktiman', 'michael,jackson', 'peter,parker', 'iron,man',
       'abc,xyz'], dtype='<U17')

In [ ]:
x = np.array([['peter', 'parker'], ['michael', 'jackson'], ['abc', 'xyz'], ['iron', 'man'], ['captain', 'shaktiman']])